# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Niko Niittyranta
email: nniittyr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Young junior developer. Interested in web development ( ie. python, django, PHP, javascript, html, css.)
  Currently working as Customer Process Specialist but always looking for new opportunities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "nikomon.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  nikomon

# Build settings
markdown: kramdown
